### PR TITLE
Improve Bag-It Profile form for Manifests Allowed

### PR DESCRIPTION
**Pull request by HaSistrunk**
Fixes issue #407 

- Changes the help text for the ManifestsRequired and ManifestsAllowed elements in the BagIt Profile form to reflect recent changes to these after we excluded md5 from the checksum algorithms.
- Shortens some help text in the BagIt Profile form.

Question: I think we should make Manifests Allowed required in the form? I could not figure out how to do that, so tips welcome.

### CODE REVIEW

**Review by p-galligan — APPROVED** [review]

**Comment by helrond** [comment]
@HaSistrunk I agree it's a good idea to make Manifests Allowed a required field. I think you'd do that by using `validate_min` on the `ManifestsAllowedFormset` (in bag_transfer/orgs/form.py)

(see https://docs.djangoproject.com/en/2.2/topics/forms/formsets/#validate-min)

**Comment by helrond** [comment]
@HaSistrunk I also just noticed an error I introduced in `orgs/views.py`, and I think it could be fixed in this PR.

Line 258 currently read
```
"manifests__allowed_formset": ManifestsAllowedFormset(
```
which should instead be
```
"manifests_allowed_formset": ManifestsAllowedFormset(
```
Note the extra underscore.

**Review by bonniegee — APPROVED** [review]

**Comment by HaSistrunk** [comment]
This does validate and throws an error when the form is submitted if there is no Manifest Allowed value, but the UI is showing two empty fields immediately before the user adds one (not the worst thing, but a little rough), and I'm trying to figure out how to get a asterisk after the form label and a better visual error message like the accession forms have.

**Comment by HaSistrunk** [comment]
@helrond, I'm getting stuck on the final pieces of this: 
1. Indicating it is a required field (the other required fields have the asterisk as specified in `bag_info-formfields.html`, but I'm not sure how to map this to the ManifestsAllowed field).
2. Styling the error that appears when the user submits the form without specifying a value in the ManifestsAllowed field. It should be `class="help-block"`, but I'm not sure how to implement that.

**Comment by helrond** [comment]
@HaSistrunk I think you need to just do two things:

- On line 27 just add an asterisk after the field name
- Delete line 29 and instead add the following at line 33 (underneath the current help block text):
```
{% if manifests_allowed_formset.non_form_errors %}
  {% for error in manifests_allowed_formset.non_form_errors %}
    <p class="help-block">{{ error }}</p>
  {% endfor %}
{% endif %}
```

**Comment by HaSistrunk** [comment]
Cool, thanks @helrond - incorporated those changes and another change to get the styling together. The build is failing in a way I don't understand: 
```FAIL: test_bagitprofiles (bag_transfer.test.test_bagitprofiles.BagItProfileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/aurora/bag_transfer/test/test_bagitprofiles.py", line 195, in test_bagitprofiles
    self.assertEqual(update_request.status_code, 302, "Request was not redirected")
AssertionError: 200 != 302 : Request was not redirected

**Comment by helrond** [comment]
@HaSistrunk the data that was being submitted in the test for the edit view was removing the Manifests Allowed field, which meant that the form wasn't being properly submitted.

I've fixed that, plus tightened up the view a bit (there was a lot of unnecessary code) so this should be good to go.

**Review by helrond — APPROVED** [review]

**Pull request merged**
