### PR TITLE
Limits organizations to only one Bagit Profile

### LINKED ISSUE #399: Limit organizations to only one BagIt Profile
## Is your feature request related to a problem? Please describe.
The original implementation of Aurora allowed organizations to have multiple BagIt Profiles. However, we so far don't have a use case for multiple Profiles associated with a single organization. 

Having multiple BagIt Profiles associated with an organization also blocks us from doing some things which would improve validation, like dynamically fetching the BagIt Profile's URL from Aurora, rather than having to rely on hardcoded URLs.

## Describe the solution you'd like
Remove the ForeignKey relationship on BagItProfiles to Organizations, and add a ForeignKey relationship from Organizations to BagIt Profiles. 
In BagIt Profile validation, fetch the BagIt Profile by using Django's `reverse` utility.
Additional work will need to be done in Views, Templates and API Serializers to account for the above changes.

## Describe alternatives you've considered
We could leave this as-is; it's not necessarily hurting anyone, but it's kind of annoying.

### PR DESCRIPTION
**Pull request by helrond**
Limits organizations to one BagIt Profile by changing database relationships. Makes a bunch of other updates throughout the app as a result of this change.

**Note for reviewers**: this is a pretty intensive PR, so please take the time to pull down the app and test things out locally to make sure it's all working as expected.

fixes #399

### CODE REVIEW

**Comment by p-galligan** [comment]
@helrond I'm not sure if this is really related to this change, but I noticed something weird in the `/admin` view of BagIt profiles. I deleted the BagIt profile associated with the donor org, and then made a new one. In the BagIt profile information on the `/admin` page, the drop-down menu defaults to Archival Repository instead of Donor Organization. Not sure if that matters to us or not, but thought I should point it out. The profile still shows up under the donor organization in the app view though.

**Comment by helrond** [comment]
@p-galligan are you talking about the Django admin interface? If so I'm not super concerned about that; more about what happens when you create a new profile from the organization page.

**Comment by p-galligan** [comment]
@helrond Yep, that's what I meant. Otherwise things seem to be working fine.

**Review by p-galligan — APPROVED** [review]

**Comment by bonniegee** [comment]
When I tried to test this, I got an error at login: "OperationalError at /login/

(1054, "Unknown column 'bag_transfer_organization.bagit_profile_id' in 'field list'")"

I ran docker-compose build before running docker-compose up to test; is there an additional command that I need to run?

**Comment by bonniegee** [comment]
This mostly works okay, but when there is already a BagIt Profile attached to an organization, there is still a button to add a new BagIt Profile. This edits the existing BagIt Profile, but I'm wondering if the button should not be there if there is already a profile?

Additionally, this might warrant a new issue, but I'm wondering about the utility of the description field if there's only one BagIt Profile per organization.

**Comment by HaSistrunk** [comment]
Yeah, this is working ok for me! I noticed the same as Bonnie re: the button to add a new profile could maybe be made inactive once a profiles already exists?

I noticed a separate issue in the BagIt Profile, which is that the user can only 2 two 'BagIt Versions Accepted," even though there are 3 options in the form. I can add an issue for that.

**Review by HaSistrunk — APPROVED** [review]

**Comment by helrond** [comment]
@bonniegee Thanks, good catch! I've added a commit that addresses that issue by hiding/showing the button based on whether or not there's an existing BagIt Profile (this was actually already there, I just needed to modify the query it was using). I also removed the description - it's technically part of the BagIt Profile spec, but you're right, there's not much use for it in the UI.

**Review by bonniegee — APPROVED** [review]

**Pull request merged**
