### PR TITLE
Implement PageTitleMixin

### LINKED ISSUE #473: Add meta page title mixin
## Is your feature request related to a problem? Please describe.
A number of views require overriding `get_context_data` just to set the meta page title.

## Describe the solution you'd like
Create a mixin (like Aquila's PageTitleMixin).

### PR DESCRIPTION
**Pull request by helrond**
Adds a PageTitleMixin and implements it across the application. This means that all pages now have a meta page title which aligns with the `h1` on the page. It also allowed me to get rid of some `get_context_data` blocks in views, which was a nice feeling.

Asking for a review on this because it's fairly invasive. 

Fixes #473

### CODE REVIEW

**Review by p-galligan — APPROVED** [review]

**Review by bonniegee — APPROVED** [review]

**Comment by HaSistrunk** [comment]
I was able to build fine, but when opening the app in the browser, I got a 403 error after I tried to sign into admin. "CSRF token missing or incorrect."

**Comment by HaSistrunk** [comment]
I'm seeing all those great page titles showing up except in the `/api` and `/api/schema/` pages, which are just showing "Aurora" but not the h1-aligned part.

**Comment by helrond** [comment]
good catch @HaSistrunk - that latest commit should have fixed that.

**Comment by HaSistrunk** [comment]
> good catch @HaSistrunk - that latest commit should have fixed that.

I can't figure out why, because this fix makes sense to me, but I'm still seeing just "Aurora" in the `<title>` in the `<head>` after rebuilding for the api.

**Comment by helrond** [comment]
Hmm, I can't reproduce that. Did you try clearing your browser cache?

Screen Shot 2021-07-16 at 11 44 19 AM

**Comment by HaSistrunk** [comment]
Cache was cleared, turns out it was some git chaos I created for myself locally that I won't bore you with. All good!

**Review by HaSistrunk — APPROVED** [review]

**Pull request merged**
