### PR TITLE
Scope Dashboard Record Type to only show record types of transfers for an organization

### LINKED ISSUE #408: Dashboard record type data should be scoped to selected organization
## Describe the bug
When looking at dashboard data, a user with organization scope (i.e. anyone other than an archivist) should only see the record types associated with a selected organization.

Screen Shot 2020-05-12 at 3 52 55 PM
This organization only has one record type uploaded, we should only see that one!

Related to #341 (probably)

### PR DESCRIPTION
**Pull request by p-galligan**
Adding a filter to record type data in views to only show in organization data. Fixes #408 .

### CODE REVIEW

**Comment by p-galligan** [comment]
I tested this by creating a new org with no transfer, and then moving the donor user to the new organization. When on the new organization, no RecordTypeData was shown on the dashboard. 

I believe this meets the requirements for #408 .

**Comment by helrond** [comment]
I added a conditional so that record types with a zero count for an organization aren't shown in the legend.

**Review by helrond — APPROVED** [review]
Looks good, thanks @p-galligan

**Comment by p-galligan** [comment]
Thanks! I missed that.

**Review by HaSistrunk — APPROVED** [review]

**Review by bonniegee — APPROVED** [review]

**Pull request merged**
