### PR TITLE
Add privacy policy link to footer

### LINKED ISSUE #445: Add link to Privacy Policy
## Describe the solution you'd like
Add a link in the footer to the [RAC Privacy Policy](https://rockarch.org/about-us/privacy-policy/).

### PR DESCRIPTION
**Pull request by bonniegee**
Fixes #445

### CODE REVIEW

**Comment by HaSistrunk** [comment]
Looking at this fresh after a long while, what if we took this opportunity to streamline things in the footer a bit and clean it up?
```
<footer class="main-footer" role="contentinfo">
  <p>
    <a href="http://rockarch.org/" class="logo-lg">
      <img src="{% static "dist/img/RAC-logo.png" %}" alt="The Rockefeller Archive Center">
    </a>
    Rockefeller Archive Center.
    <a href="https://github.com/RockefellerArchiveCenter/aurora/blob/base/LICENSE">MIT License</a>
    | <a href="https://rockarch.org/about-us/privacy-policy/">Privacy Policy</a>
  </p>
</footer>

**Comment by helrond** [comment]
Errr the build is failing because there are references to the `master` branch in sample bags.

**Comment by HaSistrunk** [comment]
Looks good to me! Only small thing I see are some indentation adjustments: The paragraph should be inside the footer and everything else should be inside the paragraph:
```
<footer>
    <p>
        content
    </p>
</footer>

**Comment by HaSistrunk** [comment]
> Errr the build is failing because there are references to the `master` branch in sample bags.

Oops, I did not catch this before, and also made changes to the readme reference to master in `base`, but not `v2.1`.

**Comment by helrond** [comment]
@HaSistrunk I picked that up in another branch. I've got a PR coming which should get tests working again 🤞

**Review by helrond — APPROVED** [review]

**Review by HaSistrunk — APPROVED** [review]

**Pull request merged**
